import type { SourceConfig } from "@/types/source";

export interface SourceDefinition extends SourceConfig {
  description: string;
}

export const seedSources: SourceDefinition[] = [
  {
    name: "Svemo",
    slug: "svemo",
    url: "https://www.svemo.se",
    feedUrl: null,
    region: "sweden",
    sportFocus: "general",
    parserKey: "svemo",
    isOfficial: true,
    pollingIntervalMinutes: 60,
    description: "Swedish Motorcycle and Snowmobile Federation",
  },
  {
    name: "FIM News",
    slug: "fim-news",
    url: "https://www.fim-moto.com",
    feedUrl: null,
    region: "global",
    sportFocus: "general",
    parserKey: "fim-news",
    isOfficial: true,
    pollingIntervalMinutes: 120,
    description: "Fédération Internationale de Motocyclisme",
  },
  {
    name: "FIM Enduro",
    slug: "fim-enduro",
    url: "https://www.fim-moto.com/en/sport/enduro",
    feedUrl: null,
    region: "global",
    sportFocus: "enduro",
    parserKey: "fim-enduro",
    isOfficial: true,
    pollingIntervalMinutes: 120,
    description: "FIM Enduro World Championship Coverage",
  },
  {
    name: "DEM",
    slug: "dem",
    url: "https://www.enduro-dm.de",
    feedUrl: null,
    region: "europe",
    sportFocus: "enduro",
    parserKey: "dem",
    isOfficial: false,
    pollingIntervalMinutes: 180,
    description: "Deutsche Enduro Meisterschaft",
  },
  {
    name: "EnduroGP",
    slug: "endurogp",
    url: "https://www.endurogp.com",
    feedUrl: null,
    region: "global",
    sportFocus: "enduro",
    parserKey: "endurogp",
    isOfficial: true,
    pollingIntervalMinutes: 120,
    description: "Enduro World Championship",
  },
  {
    name: "SuperEnduro",
    slug: "superenduro",
    url: "https://superenduro.org",
    feedUrl: null,
    region: "global",
    sportFocus: "enduro",
    parserKey: "superenduro",
    isOfficial: true,
    pollingIntervalMinutes: 180,
    description: "FIM SuperEnduro World Championship",
  },
  {
    name: "MXGP",
    slug: "mxgp",
    url: "https://www.mxgp.com",
    feedUrl: null,
    region: "global",
    sportFocus: "motocross",
    parserKey: "mxgp",
    isOfficial: true,
    pollingIntervalMinutes: 60,
    description: "FIM Motocross World Championship — MXGP and MX2",
  },
  {
    name: "Race Magazine",
    slug: "racemagazine",
    url: "https://www.racemagazine.se",
    feedUrl: null,
    region: "sweden",
    sportFocus: "general",
    parserKey: "racemagazine",
    isOfficial: false,
    pollingIntervalMinutes: 60,
    description: "Swedish motorsport journalism — motocross, enduro, and off-road",
  },
];
